version: "3.7"
services:
  mongo:
    image: mongo
    volumes:
    - "mongo:/data/db"
  recog:
    build:
      context: .
      args:
        MODE_ENV: production
    restart: always
    depends_on:
    - mongo
volumes:
  mongo:
